name: Run tests

on:
  pull_request:
    branches:
      - main

  # Allows manual run from the Actions tab
  workflow_dispatch:

  # Allows re-use in other workflows
  workflow_call:

jobs:
  run-tests:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 8
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.11', '3.13', '3.14']
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          lfs: true
      - name: Setup python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test]
      - name: Run tests
        run: |
          python3 -m pytest --dist loadfile -v --junitxml="test_results.xml"
        working-directory: ./tests
      - name: run new_frame and available_parameters script
        run:  |
          python -m emodpy_workflow.scripts.new_frame --country Zambia --dest baseline
          python -m emodpy_workflow.scripts.available_parameters -f baseline
        working-directory: ./examples/zambia
      - name: run scripts.download
        run:  python -m emodpy_workflow.scripts.download -h
        working-directory: ./examples/zambia
      - name: run scripts.calibrate
        run:  python -m emodpy_workflow.scripts.calibrate -h
        working-directory: ./examples/zambia
      - name: run scripts.resample
        run:  python -m emodpy_workflow.scripts.resample -h
        working-directory: ./examples/zambia
      - name: scripts.run
        run: python -m emodpy_workflow.scripts.run -h
        working-directory: ./examples/zambia
      - name: scripts.extend_frame
        run: python -m emodpy_workflow.scripts.extend_frame --source baseline --dest scenario1
        working-directory: ./examples/zambia
